all:
	gcc -c -mcmodel=large -fno-stack-protector -I ../../include perma_frighten.c
	gcc -c -mcmodel=large -fno-stack-protector -I ../../include pacman_immortal.c
	gcc -c -mcmodel=large -fno-stack-protector -I ../../include pacman_edit_lives.c

clean:
	rm -f *.o
